name: Auto-Upload

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with: 
          flags: '-lrvuO --delete'
          options: '../workspace'
          ssh_options: '-q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
          src: '.'
          dest: '${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.EDITOR_HELP_REMOTE }}'
